runtime: python38

instance_class: F2

entrypoint: gunicorn -c setup.ini {{ project_name }}.wsgi

automatic_scaling:
  min_instances: 1
  max_instances: 2

includes:
  - .env.yaml

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
  
  - url: /static
    static_dir: static/